#!/usr/bin/env bash
set -euo pipefail
usage(){ echo 'Usage: WAF_RELEASE_SIGNING_KEY=/path/key.pem ./sign-release-artifact.sh <artifact> [signature]' >&2; }
[[ $# -ge 1 && $# -le 2 ]] || { usage; exit 2; }
artifact=$1; sig=${2:-$artifact.sig}
[[ -f "$artifact" ]] || { echo "ERROR: artifact not found: $artifact" >&2; exit 1; }
key=${WAF_RELEASE_SIGNING_KEY:-}
[[ -n "$key" && -f "$key" ]] || { echo 'NOT_RUN: WAF_RELEASE_SIGNING_KEY is not configured; no signing key is shipped or generated by this project' >&2; exit 3; }
command -v openssl >/dev/null || { echo 'ERROR: openssl unavailable' >&2; exit 1; }
umask 077
openssl dgst -sha256 -sign "$key" -out "$sig" "$artifact"
sha256sum "$artifact" > "$artifact.sha256"
echo "SIGNED $artifact -> $sig"
