#!/usr/bin/env python3
from pathlib import Path
import hashlib,json,sys
R=Path(__file__).resolve().parents[1]
checks=[]
def ok(name,cond): checks.append((name,bool(cond)))
def text(p): return (R/p).read_text(encoding='utf-8',errors='replace')
h=text('dashboard_connector_http.go'); st=text('dashboard_connector_store.go'); ex=text('dashboard_connector_export.go'); m=text('main.go'); tok=text('tools/waf_dashboard_token.py')
ok('fixed-prefix', 'owiBasePath' in text('dashboard_connector_types.go') and '"/api/integrations/dashboard/v1"' in text('dashboard_connector_types.go'))
for route in ['health','capabilities','assets','detections','policies','health-observations','events','action-status']:
 ok('route-'+route, 'owiBasePath+"/'+route+'"' in h)
ok('opaque-bearer', '"opaque_bearer"' in h and 'Bearer ' in h)
ok('no-admin-auth-reuse', 'adminToken' not in h and 'session' not in h.lower())
ok('digest-domain-separation', 'waf-proxy/dashboard-reader-token/v1' in h and 'digest_sha256' in tok)
ok('token-expiry-revoke', 'RevokedAt' in h and 'ExpiresAt' in h and 'NotBefore' in h)
ok('rotation-overlap', 'timedelta(hours=24)' in tok)
ok('per-identity-limit', 'p.TenantID+"\\x00"+p.Principal' in h)
ok('global-concurrency', 'globalMax' in h)
ok('server-deadline', 'context.WithTimeout' in h)
ok('snapshot-count-cap', 'snapshot count capacity exceeded' in st)
ok('snapshot-record-cap', 'snapshot record capacity exceeded' in st)
ok('snapshot-byte-cap', 'snapshot byte capacity exceeded' in st)
ok('export-row-cap', 'DetectionMaxRows' in st)
ok('export-byte-cap', 'DetectionMaxBytes' in st)
ok('durable-state', 'atomicWriteJSON' in st and 'CleanShutdown' in st)
ok('gap-on-drop', 'markDetectionDrop' in ex and 'coverage gap' in ex)
ok('nonblocking-hot-path', 'default:' in ex and 'p.dropped.Add(1)' in ex)
ok('query-sanitization', 'safeOWIPath' in ex and "IndexByte(raw, '?')" in ex)
ok('phase-a-actions-empty', '[]string{}' in h and 'Actions' in text('dashboard_connector_types.go'))
ok('optional-disabled', 'CAPABILITY_UNAVAILABLE' in h and 'NOT_IMPLEMENTED' in h)
ok('strict-get-only', 'exact GET-only machine-reader contract' in h and h.count('r.Method != http.MethodGet') >= 3)
ok('disabled-scopes-unprovisioned', 'ALL_SCOPES = set(DEFAULT_SCOPES)' in tok and 'owiScopeEvents: true' not in h and 'owiScopeActionState: true' not in h)
ok('secret-files-owner-only-nonsymlink', 'os.Lstat' in h and 'owner-only non-symlink' in h and 'os.Lstat' in st and 'owner-only non-symlink' in st)
ok('management-tls-min12', 'MinVersion: tls.VersionTLS12' in m)
ok('drain-persistence-gap', 'dashboard detection export drain persistence failed' in ex and 'p.store.markDetectionDrop()' in ex)
ok('context-aware-store-lock', 'lockContext' in st and 'TryLock' in st and 'syncStateBatchContext(ctx' in ex)
ok('durability-write-fail-closed', 'writeFailed' in st and 'dashboard connector durability is unavailable' in st and 'changed || s.writeFailed' in st)
ok('main-wiring', 'loadOWIConnectorConfig' in m and 'newOWIConnector' in m and 'owiPlaneCheck' in m)
ok('return-package', (R/'return/waf-proxy/fixture-bundle.json').is_file() and (R/'return/waf-proxy/SHA256SUMS').is_file())
ok('no-api9', 'API9' not in h+st+ex+text('dashboard_connector_types.go'))
failed=[n for n,v in checks if not v]
for n,v in checks: print(('PASS' if v else 'FAIL'),n)
print(f'TOTAL={len(checks)} PASS={len(checks)-len(failed)} FAIL={len(failed)}')
if failed: print('FAILED='+','.join(failed)); sys.exit(1)
